name: pull-request-workflow
on: pull_request

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello word
    - name: step2
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.sha }}
        echo ${{ github.ref }}
        echo "This is a GitHub Action"